
# Use logger settings for Spring same as for Ignite.
logging.config: classpath:META-INF/log4j2.xml

# Uncomment for migration of user data from MongoDB.
#migration.mongo.db.url: mongodb://localhost:27018/console

# Uncomment for HTTPS:
server:
  port: 3000
#  port: 443
#  ssl:
#    key-store-type: JKS
#    key-store: certificates/server.jks
#    key-store-password: change_me
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

  mail:
    defaultTemplatePath: templates/mail/base.html
